spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/swiftride
    username: postgres
    password: asmaa123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
