server:
  port: 8088
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.show_sql: true


debug: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
